# generated by Claude Opus 5.5

dat_wide <- make_wq_wide()
dat_long <- make_wq_long()

panel_labels <- function(p) {
  as.character(ggplot2::ggplot_build(p)$layout$layout$variable_label)
}

test_that("ss_ggplot_variables() returns a ggplot that renders, from wide data", {
  p <- ss_ggplot_variables(dat_wide)

  expect_s3_class(p, "ggplot")
  expect_renders(p)
  expect_equal(
    panel_labels(p), c("Temperature (°C)", "Dissolved Oxygen (% sat)")
  )
})

test_that("ss_ggplot_variables() gives the same panels from long data", {
  p_long <- ss_ggplot_variables(dat_long)

  expect_s3_class(p_long, "ggplot")
  expect_equal(panel_labels(p_long), panel_labels(ss_ggplot_variables(dat_wide)))
  expect_equal(nrow(p_long$data), nrow(dat_long))
})

test_that("ss_ggplot_variables() colours by depth with the default palette", {
  p <- ss_ggplot_variables(dat_wide)
  b <- ggplot2::ggplot_build(p)

  # three depths, shallowest gets the first palette colour
  pal <- ss_get_colour_palette(dat_wide)
  expect_setequal(unique(b$data[[1]]$colour), pal[1:3])
  expect_true(is.ordered(p$data$sensor_depth_at_low_tide_m))
  expect_equal(levels(p$data$sensor_depth_at_low_tide_m), c("2", "5", "10"))
})

test_that("ss_ggplot_variables() uses a user-supplied palette", {
  pal <- c("#000000", "#FF0000", "#0000FF")
  b <- ggplot2::ggplot_build(ss_ggplot_variables(dat_wide, colour_palette = pal))

  expect_setequal(unique(b$data[[1]]$colour), pal)
})

test_that("ss_ggplot_variables() puts units on a new line with yaxis_newline = TRUE", {
  p <- ss_ggplot_variables(dat_wide, yaxis_newline = TRUE)

  expect_equal(
    panel_labels(p), c("Temperature \n(°C)", "Dissolved Oxygen \n(% sat)")
  )
})

test_that("ss_ggplot_variables() can colour by serial number", {
  p <- ss_ggplot_variables(dat_wide, colour_col = "sensor_serial_number")
  b <- ggplot2::ggplot_build(p)

  expect_s3_class(p$data$sensor_serial_number, "factor")
  expect_setequal(
    unique(b$data[[1]]$colour), RColorBrewer::brewer.pal(8, "Dark2")[1:3]
  )
  expect_renders(p)
})

test_that("ss_ggplot_variables() works without the sensor and depth columns", {
  dat <- select(dat_wide, timestamp_utc, temperature_degree_c)

  p <- ss_ggplot_variables(dat, colour_palette = "#000000")
  expect_renders(p)
})

test_that("ss_ggplot_variables() adds superchill shading when temperature is <= -0.7", {
  has_rect <- function(p) {
    any(vapply(p$layers, function(l) inherits(l$geom, "GeomRect"), logical(1)))
  }

  expect_true(has_rect(ss_ggplot_variables(make_wq_wide(min_temp = -1))))
  expect_true(has_rect(ss_ggplot_variables(make_wq_wide(min_temp = -0.7))))
  expect_false(has_rect(ss_ggplot_variables(make_wq_wide(min_temp = 0))))

  # the superchill argument overrides the data
  expect_false(
    has_rect(ss_ggplot_variables(make_wq_wide(min_temp = -1), superchill = FALSE))
  )
  expect_true(
    has_rect(ss_ggplot_variables(make_wq_wide(min_temp = 0), superchill = TRUE))
  )
  expect_renders(ss_ggplot_variables(make_wq_wide(min_temp = -1)))
})

test_that("ss_ggplot_variables() places the legend", {
  p <- ss_ggplot_variables(dat_wide, legend_position = "bottom")

  expect_equal(p$theme$legend.position, "bottom")
  expect_renders(p)
})

test_that("ss_ggplot_variables() includes the tooltip text for ggplotly()", {
  p <- ss_ggplot_variables(dat_wide)

  expect_true("text" %in% names(p$mapping))
})

test_that("ss_ggplot_variables() accepts data with timestamp_ast", {
  p <- ss_ggplot_variables(make_wq_wide(ts_col = "timestamp_ast"))
  expect_renders(p)
})

test_that("ss_ggplot_variables() respects a user palette with colour_col = 'sensor_serial_number'", {
    pal <- c("#000000", "#FF0000", "#0000FF")
  b <- ggplot2::ggplot_build(
    ss_ggplot_variables(
      dat_wide, colour_col = "sensor_serial_number", colour_palette = pal
    )
  )
  expect_setequal(unique(b$data[[1]]$colour), pal)
})

