# generated by Claude Opus 5.5

# ss_plot_variables() calls theme_set(); the theme is restored at the end of
# this file
old_theme <- ggplot2::theme_get()

dat_wide <- make_wq_wide()

# Return the list of panels that ss_plot_variables() passes to ggarrange()
plot_panels <- function(...) {
  local_mocked_bindings(
    ggarrange = function(plotlist, ...) plotlist,
    .package = "sensorstrings"
  )
  ss_plot_variables(...)
}

y_label <- function(p) as.character(ggplot2::get_labs(p)$y)
y_limits <- function(p) ggplot2::layer_scales(p)$y$limits

test_that("ss_plot_variables() returns a ggarrange figure that renders", {
  p <- ss_plot_variables(dat_wide)

  expect_s3_class(p, "ggarrange")
  expect_renders(p)
})

test_that("ss_plot_variables() makes one panel per variable, in standard order", {
  panels <- plot_panels(dat_wide)

  expect_length(panels, 2)
  expect_equal(
    vapply(panels, y_label, character(1)),
    c("Temperature (°C)", "Dissolved Oxygen (% sat)")
  )
})

test_that("ss_plot_variables() gives the same panels from long data", {
  panels_long <- plot_panels(ss_pivot_longer(dat_wide))

  expect_equal(
    vapply(panels_long, y_label, character(1)),
    vapply(plot_panels(dat_wide), y_label, character(1))
  )
})

test_that("ss_plot_variables() drops flag columns and non-variable columns", {
  dat <- dat_wide %>% mutate(qc_flag_temperature_degree_c = 1)

  expect_length(plot_panels(dat), 2)
})

test_that("ss_plot_variables() handles more than four panels", {
  dat <- dat_wide %>%
    mutate(salinity_psu = 30, ph_ph = 8, sensor_depth_measured_m = 2)

  panels <- plot_panels(dat)
  expect_length(panels, 5)
  expect_renders(ss_plot_variables(dat))
})

test_that("ss_plot_variables() puts units on a new line with yaxis_newline = TRUE", {
  panels <- plot_panels(dat_wide, yaxis_newline = TRUE)

  expect_equal(y_label(panels[[1]]), "Temperature \n(°C)")
})

test_that("ss_plot_variables() sets standard y-limits that can be turned off or replaced", {
  dat <- dat_wide %>% mutate(salinity_psu = 30, ph_ph = 8)
  find_panel <- function(panels, label) {
    panels[[which(vapply(panels, y_label, character(1)) == label)]]
  }

  std <- plot_panels(dat)
  expect_equal(y_limits(find_panel(std, "pH")), c(7.5, 8.5))
  expect_equal(y_limits(find_panel(std, "Salinity (PSU)")), c(25, 34))
  # temperature has no standard limits
  expect_null(y_limits(find_panel(std, "Temperature (°C)")))

  off <- plot_panels(
    dat,
    standard_do_ylims = FALSE, standard_ph_ylims = FALSE,
    standard_sal_ylims = FALSE
  )
  expect_null(y_limits(find_panel(off, "pH")))
  expect_null(y_limits(find_panel(off, "Salinity (PSU)")))
  expect_null(y_limits(find_panel(off, "Dissolved Oxygen (% sat)")))

  custom <- plot_panels(
    dat,
    standard_do_ylims = c(50, 150), standard_ph_ylims = c(7, 9),
    standard_sal_ylims = c(20, 35)
  )
  expect_equal(y_limits(find_panel(custom, "pH")), c(7, 9))
  expect_equal(y_limits(find_panel(custom, "Salinity (PSU)")), c(20, 35))
  expect_equal(y_limits(find_panel(custom, "Dissolved Oxygen (% sat)")), c(50, 150))
})

test_that("ss_plot_variables() uses mg/L limits for dissolved_oxygen_mg_per_l", {
  dat <- dat_wide %>%
    select(-dissolved_oxygen_percent_saturation) %>%
    mutate(dissolved_oxygen_mg_per_l = 9)

  expect_equal(y_limits(plot_panels(dat)[[2]]), c(0, 15))
})

test_that("ss_plot_variables() colours by depth", {
  pal <- c("#000000", "#FF0000", "#0000FF")
  panels <- plot_panels(dat_wide, color_palette = pal)
  b <- ggplot2::ggplot_build(panels[[1]])

  expect_setequal(unique(b$data[[1]]$colour), pal)
})

test_that("ss_plot_variables() passes the legend position to ggarrange()", {
  args <- NULL
  local_mocked_bindings(
    ggarrange = function(...) args <<- list(...),
    .package = "sensorstrings"
  )
  ss_plot_variables(dat_wide, legend_position = "bottom")

  expect_equal(args$legend, "bottom")
  expect_true(args$common.legend)
})

test_that("ss_plot_variables() sets the DO limits given in the help page", {
  expect_equal(y_limits(plot_panels(dat_wide)[[2]]), c(60, 160))
})


test_that("ss_plot_variables() plots tilt_degree", {
  dat <- dat_wide %>% mutate(tilt_degree = 5)
  expect_length(plot_panels(ss_pivot_longer(dat)), 3)
})

test_that("ss_plot_variables() plots dissolved_oxygen_uncorrected_mg_per_l from wide data", {
 # skip("Known bug SS-12: the wide path drops dissolved_oxygen_uncorrected_mg_per_l")

  dat <- dat_wide %>% mutate(dissolved_oxygen_uncorrected_mg_per_l = 9)
  expect_length(plot_panels(dat), 3)
})

test_that("ss_plot_variables() accepts data with timestamp_ast", {
  expect_renders(ss_plot_variables(make_wq_wide(ts_col = "timestamp_ast")))
})

ggplot2::theme_set(old_theme)
